### ISSUE TITLE
battery object missing

### ISSUE THREAD

**Issue by daniel-lo** [Chris-1965/ioBroker.fitbit-fitness#2]
Hi .. thanks for this adapter .. from the old adapter the only object I used was the battery object .. would it be possible to add this here too? 
![grafik](https://user-images.githubusercontent.com/4311558/191185213-718baf69-d0e1-46c9-a0aa-860ebba775fb.png)

Best regards

**Comment by Chris-656** [comment]
I will plan it in the next version 😊

Regards Chris

 

Von: daniel-lo ***@***.***> 
Gesendet: Dienstag, 20. September 2022 08:40
An: Chris-1965/ioBroker.fitbit-fitness ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Chris-1965/ioBroker.fitbit-fitness] battery object missing (Issue #2)

 

Hi .. thanks for this adapter .. from the old adapter the only object I used was the battery object .. would it be possible to add this here too?
 <https://user-images.githubusercontent.com/4311558/191185213-718baf69-d0e1-46c9-a0aa-860ebba775fb.png> 

Best regards

**Comment by Chris-656** [comment]
Try the new version I added the baterystatus of the entire devices.
regards Chris

**Comment by daniel-lo** [comment]
Thanks @Chris-1965 .. "indicator.lowbat" is now a value an not true/false anymore. I don't acutally have a spontaneous opinion whether this is good or bad .. but I am grateful that you implemented it :-)
Might it be a good idea to have a batt level value and an indicator whether one should change batteries?

These are my current objects:
![grafik](https://user-images.githubusercontent.com/4311558/191320673-95c46c23-f930-45cb-86d0-5ba037d0c14f.png)

**Comment by Chris-656** [comment]
solved
