### ISSUE TITLE
(null) No values problem in ioBroker

### ISSUE THREAD

**Issue by KaeptnKluk** [Chris-1965/ioBroker.fitbit-fitness#3]
Hello,

you can see my problem already in the screenshot. Some values are not retrieved. The token is up to date. Do you have any idea what else I can try?

![image](https://user-images.githubusercontent.com/36924212/191218895-527e47da-1491-46bd-8672-8e821dfa65c7.png)

 - Adapter version: v0.4.6
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Docker (unraid)

**Comment by Chris-656** [comment]
Ok lets see. Do have the update of the fitbit app on your phone. The only aria has a wifi connection. So when the values are in the fitbitapp synced they should appear also in the adapter.
Check that we will see then.
regards Chris

**Comment by KaeptnKluk** [comment]
There was actually an update to the app coming up. Unfortunately, the values are still not updated. Is the Body section only updated with the Aria or Aria2? Currently I enter my values in the app by hand. However, these are not transferred. It looks like the values were only retrieved once and then not updated. The adapter shows no problems and I have already regenerated the tokens.

**Comment by KaeptnKluk** [comment]
![image](https://user-images.githubusercontent.com/36924212/191242315-e3a239d5-2f2b-44c0-a1b7-afd24cef72b8.png)

![image](https://user-images.githubusercontent.com/36924212/191242332-77027cac-24bc-4aa5-9444-42cab0e0da63.png)

![image](https://user-images.githubusercontent.com/36924212/191242367-effa4502-9189-4b56-b10f-9ecc64504d65.png)

![image](https://user-images.githubusercontent.com/36924212/191242782-77da3e34-16d6-4585-8e04-d8beb4efa6a0.png)

**Comment by Chris-656** [comment]
Ok thx for the info, so test the steps if you have a charge 3 or 4. If you are using the app on a samsung handy fitbit you should see a chenge in the steps and calories. if yes let me know. Normaly the retrieval should get all these values. Have you selected the records in the adapter settings  in order to retrieve the values.

![grafik](https://user-images.githubusercontent.com/56934142/191244559-666f4583-7c36-486e-8e6c-e9164d00e7e3.png)

**Comment by KaeptnKluk** [comment]
Yes, the settings should be correct. 

I have a Fitbit Versa 3 and the app runs on a Google Pixel 6 Pro. 

The values in the app update without problems

![image](https://user-images.githubusercontent.com/36924212/191245193-73fa75e0-147a-4102-ae93-fe8d5b9aa5d4.png)

**Comment by locito09** [comment]
bei mir das gleiche die Daten werden nicht abgerufen von der Aria, in der Fitbit App alles ok, mit den alten Adapter auch keine Probleme

**Comment by Chris-656** [comment]
I will check that next days. Maybe interface change at fitbit. I will then create a new version 
regards Chris

**Comment by Chris-656** [comment]
Try new Version 0.4.8 and give me feedback
r C

**Comment by KaeptnKluk** [comment]
now it's working. Thank you!

**Comment by Chris-656** [comment]
solved
