### ISSUE TITLE
Body or food data

### ISSUE THREAD

**Issue by Backfire-FF** [Chris-1965/ioBroker.fitbit-fitness#5]
**Screenshots & Logfiles**  
![fitbit_adapter](https://user-images.githubusercontent.com/66845105/204459567-d3649bf7-06c0-46b1-a67b-5eeadd4162d4.png)

**Versions:**  
 - Adapter version: v0.4.6
 - JS-Controller version: 4.0.23
 - Node version: v14.21.1
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Additional context**  
The adapter doesn't sync any body or food data.

Is this a known behavior?

Thanks

**Comment by Chris-656** [comment]
I will check that regards Chris

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: Danny ***@***.***>
Sent: Tuesday, November 29, 2022 7:56:00 AM
To: Chris-1965/ioBroker.fitbit-fitness ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Chris-1965/ioBroker.fitbit-fitness] Body or food data (Issue #5)


Screenshots & Logfiles
[fitbit_adapter]<https://user-images.githubusercontent.com/66845105/204459567-d3649bf7-06c0-46b1-a67b-5eeadd4162d4.png>

Versions:

  *   Adapter version: v0.4.6
  *   JS-Controller version: 4.0.23
  *   Node version: v14.21.1
  *   Operating system: Raspbian GNU/Linux 10 (buster)

Additional context
The adapter doesn't sync any body or food data.

Is this a known behavior?

Thanks

**Comment by Chris-656** [comment]
ok the body records are retrieved for my system. 
Have checked the ffod records in the settings of the adapter
![grafik](https://user-images.githubusercontent.com/56934142/204643527-ac24b23d-26c9-47e2-b2be-fd5ed1f955e4.png)

regrads Chris

**Comment by Backfire-FF** [comment]
Unchecking the values and checking them again finally fixed it.
Thanks

**Comment by Chris-656** [comment]
solved
