### ISSUE TITLE
No Token Update

### ISSUE THREAD

**Issue by locito09** [Chris-1965/ioBroker.fitbit-fitness#8]
Beim versuchen den Token updaten bekomme ich diese Fehler Version 0.4.9 
und Adapter bleibt Rot
<img width="631" alt="Screenshot 2023-02-16 185338" src="https://user-images.githubusercontent.com/77743187/219449259-d6f8c04e-85da-4bb3-a7a3-06ecc094cf2f.png">

**Comment by Chris-656** [comment]
I will check that 
Regards Chris

**Comment by Chris-656** [comment]
Try the latest version 0.4.10 and give me ffedback. Should work now
regards Chris

**Comment by locito09** [comment]
Vielen Dank, leider funktioniert der Adapter immer noch nicht, bekomme folgende Meldung

<img width="341" alt="Screenshot 2023-02-17 094106" src="https://user-images.githubusercontent.com/77743187/219596634-e410ae60-52b0-4db1-b44b-7d26f68527ba.png">

**Comment by Chris-656** [comment]
ich checke das

**Comment by Chris-656** [comment]
try it again now 
regards Chris

**Comment by locito09** [comment]
SUPER DANKE

**Comment by Chris-656** [comment]
Solved
